import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "logout": "Log out",
          "welcome": "Welcome",
          "income": "Income",
          "expenses": "Expenses",
          "balance": "Balance",
          "expense": "Expense",
          "food": "Food",
          "bills": "Bills",
          "transportation": "Transportation",
          "entertainment": "Entertainment",
          "shopping": "Shopping",
          "clothing": "Clothing",
          "insurance": "Insurance",
          "telephone": "Telephone",
          "health": "Health",
          "sport": "Sport",
          "beauty": "Beauty",
          "education": "Education",
          "gift": "Gift",
          "pet": "Pets",
          "salary": "Salary",
          "awards": "Awards",
          "grants": "Grants",
          "rental": "Rental",
          "investment": "Investment",
          "lottery": "Lottery",
          "statistics": "Statistics",
          "wanna_leave?": "Do you wanna leave ?",
          "yes": "Yes",
          "no": "No",
          "change_language": "Change language",
          "No_Data_for_this_month": "No Data for this month",
          "add": "Add",
          "details": "Details",
          "delete": "Delete",
          "delete_confirm": "Are you sure do you want to delete this transaction ?",
          "cancel": "Cancel",
          "label": "Label",
          "category": "Category",
          "amount": "Amount",
          "date": "Date",
          "edit": "Edit",
          "enter_label": "Enter a memo for your transcation",
          "enter_amount": "Enter a the amount for the transcation",
          "select_date": "SELECT DATE",
          "required_field": "Required field",
          "no_tr": "No transactions\nTap + to add one.",
          "numeric_field": "Value has to be numeric",
          "tr_limits": "Transaction limit",
          "ceiling_dt": "Ceiling in DT",
          "update_ceiling": "Ceiling updated",
          "close": "Close",
          "update": "Update",
          "ceiling": "Ceiling",
          "home1": "Home",
          "messages": "Messages",
          "groups": "Groups",
          "my_messages": "My messages",
          "people": "People",
          "no_messages": "No messages yet",
          "you": "You : ",
          "write_message": "Write a message",
          "contact_admin": "Contact the administrators",
          "no_admin": "No admin available at the moment",
          "added_grp": "Group has been successfully added",
          "delete_grp": "Delete the  group",
          "deleted_grp": "Group has been successfully deleted",
          "group_name": "Group name",
          "creation_date": "Creation date",
          "members": "Members",
          "no_grps": "You don't have any groups yet",
          "add_grp": "Add group",
          "grp_name": "Group's name",
          "delete_add": "Delete add request",
          "req_deleted": "Request deleted",
          "accept_req": "Accept request",
          "accept": "Accept",
          "no_req": "You don't have any requests yet",
          "add_members": "Add members",
          "no_users": "No users available at the moment",
          "left_grp": "You left the group",
          "leave": "Leave",
          "leave_grp": "Leave the group",
          "name": "Name",
          "req_accepted": "Request accepted",
          "saving": "Saving"
        },
        'fr': {
          "no_tr": "Aucune transaction\n Appuyez sur + pour en ajouter une.",
          "required_field": "Champ obligatoire",
          "delete_confirm": "Êtes-vous sûr de vouloir supprimer cette transaction ?",
          "select_date": "Selectionner une date",
          "enter_amount": "Saisissez une monatnt pour votre transaction",
          "enter_label": "Saisissez une libellé pour votre transaction",
          "edit": "Modifier",
          "logout": "Déconnecter",
          "welcome": "Bienvenue",
          "income": "Revenu",
          "expenses": "Charges",
          "balance": "Solde",
          "expense": "Charge",
          "food": "Nourriture",
          "bills": "Factures",
          "transportation": "Transport",
          "home": "Maison",
          "entertainment": "Divertissement",
          "clothing": "Vêtements",
          "insurance": "Assurance",
          "telephone": "Téléphone",
          "health": "Santé",
          "sport": "Sport",
          "beauty": "Beauté",
          "gift": "Cadeau",
          "pet": "Animeaux",
          "salary": "Salaire",
          "awards": "Prix",
          "grants": "Subventions",
          "rental": "Location",
          "lottery": "Lot",
          "statistics": "Statistiques",
          "wanna_leave?": "Voulez-vous partir ?",
          "yes": "Oui",
          "no": "Non",
          "change_language": "Changer la langue",
          "No_Data_for_this_month": "Pas de données pour ce mois",
          "add": "Ajouter",
          "details": "Details",
          "delete": "Supprimer",
          "cancel": "Annuler",
          "label": "Libellé",
          "category": "Catégorie",
          "amount": "Montant",
          "date": "Date",
          "numeric_field": "Valeur doit étre numérique",
          "tr_limits": "Limite de transaction",
          "ceiling_dt": "Plafond en DT",
          "update_ceiling": "Plafond  mis à jour",
          "close": "Fermer",
          "update": "Mettre à jour",
          "ceiling": "Plafond",
          "home1": "Accueil",
          "messages": "Messages",
          "groups": "Groupes",
          "my_messages": "Mes messages",
          "people": "Personnes",
          "no_messages": "Aucun message pour le moment",
          "you": "Vous :",
          "write_message": "Écrire un message",
          "contact_admin": "Contacter les administrateurs",
          "no_admin": "Aucun administrateur disponible pour le moment",
          "added_grp": "Le groupe a été ajouté avec succès",
          "delete_grp": "Supprimer le groupe",
          "deleted_grp": "Le groupe a été supprimé avec succès",
          "group_name": "Nom du groupe",
          "creation_date": "Date de création",
          "members": "Membres",
          "no_grps": "Vous n'avez pas encore de groupes",
          "add_grp": "Ajouter un groupe",
          "grp_name": "Nom du groupe",
          "delete_add": "Supprimer la demande d'ajout",
          "req_deleted": "Demande supprimée",
          "accept_req": "Accepter la demande",
          "accept": "Accepter",
          "no_req": "Vous n'avez pas encore de demandes",
          "add_members": "Ajouter des membres",
          "no_users": "Aucun utilisateur disponible pour le moment",
          "left_grp": "Vous avez quitté le groupe",
          "leave": "Quitter",
          "leave_grp": "Quitter le groupe",
          "name": "Nom",
          "req_accepted": "Invitaion accepté",
          "saving": "Epargne"
        },
      };
}
